# Generated by Django 5.0.6 on 2025-06-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='photo',
            field=models.ImageField(upload_to='learn/photo'),
        ),
    ]
